---
- name: make sure to become true
  include: ensure_become.yml

- name: install firewalld
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - firewalld

# NOTE: ipsets configuration requires firewalld is running. make sure this is so:
- name: ensure firewalld service is running
  become: true
  service:
    name: "firewalld"
    enabled: true
    state: started

- name: configure services in firewalld
  firewalld:
    service:    "{{ item.service }}"
    state:      "{{ item.state | default('enabled') }}"
    zone:       "{{ firewalld_zone }}"
    permanent:  "{{ not firewalld_testing }}"
  with_items:   "{{ firewalld_services }}"
  notify: reload firewalld

- name: configure ports in firewalld
  firewalld:
    port:       "{{ item.port }}/{{ item.protocol }}"
    state:      "{{ item.state | default('enabled') }}"
    zone:       "{{ firewalld_zone }}"
    permanent:  "{{ not firewalld_testing }}"
  with_items:   "{{ firewalld_ports }}"
  notify: reload firewalld

- name: configure ipsets in firewalld
  include: configure_ipsets.yml

- name: configure rich rules in firewalld
  firewalld:
    rich_rule:  "{{ item.rule }}"
    state:      "{{ item.state | default('enabled') }}"
    zone:       "{{ firewalld_zone }}"
    permanent:  "{{ not firewalld_testing }}"
  with_items:   "{{ firewalld_richrules }}"
  notify: reload firewalld
